runtime: python310

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always